from GraphicComponent.Root import Root

class Surface(Root):
    x: int
    y: int
    w: int
    h: int

    def __init__(self, pos:tuple or list, size: tuple or list, *args, **kwargs):...

    def pos(self) -> tuple[int, ...]:...

    def size(self) -> tuple[int][2]:...

    def set_pos(self, pos:tuple[int][2]) -> None:...

    def set_size(self, size:tuple[int][2]) -> None:...

    def set_rect(self, rect:tuple[int][4]):...

    def rect(self) -> tuple[int][4]:...

    def real_pos(self) -> tuple[int][2]:...

    def real_size(self) -> tuple[int][2]:...

    def real_rect(self) -> tuple[int][4]:...

    def is_covered(self, another: Surface = None) -> bool:...

    def is_mix(self, another: Surface = None)->bool:...

    def is_crash(self, function: any):...
