from DataType.Folder.FolderStruct_Hash import Folder, folderPath


class Registry(Folder):
    def __init__(self):...
    def __getitem__(self, __key, folder_path: folderPath = None) -> any:...
    def __setitem__(self, key, value = None, folder_path: folderPath = None) -> None:...
    def __delitem__(self, key, folder_path: folderPath = None, is_folder: bool = False) -> None:...
