

class Data:
    name: str
    value: any
    type: str
    def __init__(self, types: str, name: str, value: any = None):...

    def set_value(self, value) -> None:...

    def set_name(self, name) -> None:...

    def get_name(self) -> str:...

    def get_value(self, *args, **kwargs) -> any:...


class Folder:
    father: Folder | None
    value: dict[Data]
    name: str
    son: dict[Folder]

    def __init__(self, name: str, father: Folder = None, value: dict = None):...

    def __getitem__(self, item: str) -> any:...

    def __setitem__(self, key:str, value:any) -> None:...

    def __delitem__(self, key:str) -> None:...

    def create_folder(self, path:str) -> None:...

    def absolute_path(self, saved: list) -> str:...
